# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: golangci-lint
on:
  push:
    branches:
      - main
      - master
  pull_request:

permissions:
  contents: read
  # Optional: allow read access to pull requests. Use with `only-new-issues` option.
  # pull-requests: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        program: [cli, server]
    defaults:
      run:
        working-directory: ./${{ matrix.program }}
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/go-base

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: latest
